// Find //
	POINT_MAX,
};

// Add before //
#ifdef ENABLE_RUNE_SYSTEM
	POINT_RUNE_PAGE1_KEYSTONE1,
	POINT_RUNE_PAGE1_KEYSTONE2,
	POINT_RUNE_PAGE1_KEYSTONE3,
	POINT_RUNE_PAGE2_KEYSTONE1,
	POINT_RUNE_PAGE2_KEYSTONE2,
	POINT_RUNE_PAGE2_KEYSTONE3,
	POINT_RUNE_PAGE3_KEYSTONE1,
	POINT_RUNE_PAGE3_KEYSTONE2,
	POINT_RUNE_PAGE3_KEYSTONE3,
	POINT_RUNE_PAGE1_ROW1,
	POINT_RUNE_PAGE1_ROW2,
	POINT_RUNE_PAGE1_ROW3,
	POINT_RUNE_PAGE2_ROW1,
	POINT_RUNE_PAGE2_ROW2,
	POINT_RUNE_PAGE2_ROW3,
	POINT_RUNE_PAGE3_ROW1,
	POINT_RUNE_PAGE3_ROW2,
	POINT_RUNE_PAGE3_ROW3,
#endif